import type { Metadata } from "next";
import { Caveat_Brush } from "next/font/google";
import "./globals.css";

const caveatBrushFont = Caveat_Brush({
  variable: "--font-caveat-brush",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${caveatBrushFont.variable}`}>
        <div className="absolute inset-0">
          <div className="absolute inset-0 -z-10 h-full w-full bg-white [background:radial-gradient(125%_125%_at_50%_10%,#fff_40%,#33b3ee_100%)]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
